service: meter-reading

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: eu-west-1

functions:
  meterfunction:
    handler: app.handler

    events:
      - http:
          path: /meter-read
          method: get
      - http:
          path: /meter-read/{customerid}/{meterid}
          method: get
      - http:
          path: /meter-read
          method: post

plugins:
  - serverless-offline
