service: meter-reading

provider:
  name: aws
  runtime: nodejs6.10

stage: dev
region: eu-west-1

functions:
  Present:
    handler: handlers/meterReadingHandler.getMeterReading

    events:
      - http:
          path: /meter-read/{customerid}/{meterid}
          method: get

  Accept:
    handler: handlers/meterReadingHandler.postMeterReading

    events:
      - http:
          path: /meter-read
          method: post